DEBUG=true
NUM_DEALS = {
  [1] = { [1] = 10, [2] = 6, [3] = 6, [4] = 0 }, -- for debug
  [2] = { [1] = 10, [2] = 6, [3] = 6, [4] = 0 }, -- for debug
  [3] = { [1] = 10, [2] = 6, [3] = 6, [4] = 0 },
  [4] = { [1] =  9, [2] = 4, [3] = 4, [4] = 0 },
  [5] = { [1] =  8, [2] = 3, [3] = 3, [4] = 0 }
}

ARTISTS = {'hick','ivory','okamoto','mondrian','kaminski'}
ARTIST_ORDER = {}
for idx, artist in ipairs(ARTISTS) do
  ARTIST_ORDER[artist] = idx
end
